[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "node_modules/.bin/next start -p $PORT"
preDeployCommand = "node_modules/.bin/prisma migrate deploy"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
