ALTER TABLE "Availability" ADD COLUMN IF NOT EXISTS "startTime" TEXT;
ALTER TABLE "Availability" ADD COLUMN IF NOT EXISTS "endTime" TEXT;
ALTER TABLE "Availability" ADD COLUMN IF NOT EXISTS "notAvailable" BOOLEAN NOT NULL DEFAULT false;
